---
:globals: &globals
  :google_maps_api_key: "GOOGLE_MAPS_KEY"
  :sunlight_api_key: "SUNLIGHT_API_KEY"
  :nyt_campaign_finance_api_key: "NYTIMES_CAMPAIGN_FINANCE_KEY"

development:
  <<: *globals

test:
  <<: *globals
